#!/usr/bin/env python3
"""Test cases for the GithubOrgClient class."""

import unittest
from unittest.mock import patch
from client import GithubOrgClient
from parameterized import parameterized_class
from parameterized import parameterized
from fixtures import TEST_PAYLOAD


class TestGithubOrgClient(unittest.TestCase):
    """Test case for GithubOrgClient class."""

    @parameterized.expand([
        ("google",),
        ("abc",),
    ])
    @patch('client.get_json')
    def test_org(self, org_name, mock_get_json):
        """Test org method of GithubOrgClient class."""
        mock_get_json.return_value = {"name": org_name}
        github_client = GithubOrgClient(org_name)
        result = github_client.org()
        mock_get_json.assert_called_once_with(
            f"https://api.github.com/orgs/{org_name}"
        )
        self.assertEqual(result, {"name": org_name})

    @patch('client.GithubOrgClient.org')
    def test_public_repos_url(self, mock_org):
        """Test _public_repos_url property of GithubOrgClient class."""
        mock_org.return_value = {"public_repos": 10}
        github_client = GithubOrgClient("org_name")
        result = github_client._public_repos_url
        expected_url = "https://api.github.com/orgs/org_name/repos"
        self.assertEqual(result, expected_url)

    @parameterized.expand([
        ({"license": {"key": "my_license"}}, "my_license", True),
        ({"license": {"key": "other_license"}}, "my_license", False),
    ])
    def test_has_license(self, repo, license_key, expected):
        """Test has_license method of GithubOrgClient class."""
        github_client = GithubOrgClient("org_name")
        result = github_client.has_license(repo, license_key)
        self.assertEqual(result, expected)

    @parameterized_class(("org_payload", "repos_payload", "expected_repos",
                         "apache2_repos"),
                         [(org_payload, repos_payload, expected_repos,
                          apache2_repos)])
    